# Generated by Django 4.2.16 on 2024-12-07 14:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=api.models.user_photo_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_photo_path),
        ),
    ]
